### PR TITLE
(site/ls/role/daq-mgt) updated BTS daq to R5-V6.5

### PR DESCRIPTION
**Pull request by jgthayer**
Looking to update the BTS DAQ to R5-V6.5 in coordination with CCS.

### CODE REVIEW

**Comment by jgthayer** [comment]
Ran puppet from branch and looks fine.

**Comment by jgthayer** [comment]
Looks like I need a merge now, though.

**Comment by jhoblitt** [comment]
@jgthayer Wouldn't this put BTS ahead of TTS?

**Comment by jgthayer** [comment]
Yes, excepting that BTS is not in use, and so this is leading.

**Comment by jgthayer** [comment]
This is also why Tony and I can do this without bringing it up at CAP.

**Review by jhoblitt — APPROVED** [review]
LGTM.  The branch needs to be rebased as serveral PRs were merged minutes ago.  This will be less of a pain if we enabled github's new merge queue feature for this repo.

**Pull request merged**
