### PR TITLE
(profile::ccs::graphical) tweak installed desktop apps

### PR DESCRIPTION
**Pull request by glennmorris**
Add google-chrome, drop zoom.
There was a mild request to add the slack desktop client, but I find slack in a browser works fine on Linux.
The fact that there seems to be no active forge module for the slack client seems like a sign.

### CODE REVIEW

**Comment by glennmorris** [comment]
Hmm, puppet librarian not happy with something. It worked when I tried it in practice. :man_shrugging:

**Comment by glennmorris** [comment]
> Hmm, puppet librarian not happy with something. It worked when I tried it in practice. 🤷‍♂️

I guess the root problem is that the new google-chrome module has:
`puppetlabs/apt (>=2.0.0 <8.0.0)`
but Puppetfile has
`mod 'puppetlabs/apt', '9.1.0'`

Do we need to fork the forge chrome module and change the deps?

**Comment by jhoblitt** [comment]
> Do we need to fork the forge chrome module and change the deps?

Yes, unfortunately.  r10k gets us into trouble because it doesn't do recursive dep resolution, which is why there's a librarian-puppet CI check (r10k deploys much faster on the puppetservers though).  It looks like someone else has already started a fork as well: https://github.com/GEANT/puppet-google-chrome

I haven't looked at the changes but that geant fork may be a better starting point for a fork.

**Comment by jhoblitt** [comment]
Maybe split chrome off into its own PR for now so the rest of this can be merged?

**Comment by glennmorris** [comment]
> > Do we need to fork the forge chrome module and change the deps?
> 
> Yes, unfortunately. r10k gets us into trouble because it doesn't do recursive dep resolution, which is why there's a librarian-puppet CI check (r10k deploys much faster on the puppetservers though). It looks like someone else has already started a fork as well: https://github.com/GEANT/puppet-google-chrome
> 
> I haven't looked at the changes but that geant fork may be a better starting point for a fork.

Sadly the geant fork has the same dependency issue.

**Comment by glennmorris** [comment]
I've created a trivial fork of the google-chrome module (not sure of the etiquette) and switched to that.
It passes the tests, and works fine in practice.

**Review by jhoblitt — APPROVED** [review]
LGTM.

**Pull request merged**
