### PR TITLE
(rke) add restic backup to rke role.

### PR DESCRIPTION
**Pull request by csilva-cl**
Backup runs everyday and files are stored in aws.

### CODE REVIEW

**Review by cbarria — CHANGES_REQUESTED** [review]
PR looks good, but misses the required test for the restic class

**Review by dtapiacl — APPROVED** [review]
This looks good to me.

**Comment by csilva-cl** [comment]
> PR looks good, but misses the required test for the restic class

Thanks, you are right, totally forgot.

**Comment by csilva-cl** [comment]
Wrong button.

**Review by cbarria — APPROVED** [review]
Looks Great and does the requiered job, but test could be improved.

**Pull request merged**
