### PR TITLE
(core{01-03}.dev) Network Config and Tests

### PR DESCRIPTION
**Pull request by dtapiacl**

### CODE REVIEW

**Review by jhoblitt — COMMENTED** [review]
It would be nice if the `(...)` prefix used on the commits was the same.  Another option would be to squash the two commits in this PR together. Other than that, this looks golden.

image

**Comment by dtapiacl** [comment]
Updated the prefix for the commit to match the on of the PR. Let me know if this is correct.

**Review by cbarria — APPROVED** [review]
Looks Great 👍🏻

**Comment by jhoblitt** [comment]
@dtapiacl The `(...)` section should indicate the hiera layer, so `(node/...)` would be better.  I have been meaning to put this policy into CI but haven't gotten to it yet.  Also, you are using both `add` and `Add` in commit messages. My opinion is that consistency is king.

**Review by jhoblitt — APPROVED** [review]
LGTM.

**Pull request merged**
