### PR TITLE
(role/comcam-fp) add tcp_tweak profile for s3daemon

### PR DESCRIPTION
**Pull request by cbarria**
These are the parameters that KT requested for the lsstcam-dc Nodes.

### CODE REVIEW

**Review by dtapiacl — APPROVED** [review]
LGTM.

**Review by jhoblitt — COMMENTED** [review]
Why is this different from the existing lhn profile?

**Comment by cbarria** [comment]
> Why is this different from the existing lhn profile?

just 2 parameters are different (`net.ipv4.tcp_congestion_control` & `net.ipv4.tcp_slow_start_after_idle`)
you rather I keep the LHN and add another "profile" for these two parameters, or do I add this to the existing LHN profile?
@jhoblitt

**Comment by csilva-cl** [comment]
> > Why is this different from the existing lhn profile?
> 
> just 2 parameters are different (`net.ipv4.tcp_congestion_control` & `net.ipv4.tcp_slow_start_after_idle`) you rather I keep the LHN and add another "profile" for these two parameters, or do I add this to the existing LHN profile? @jhoblitt

we should add these 2 parameters to the lhn profile, the rest is the same.

**Comment by jhoblitt** [comment]
> just 2 parameters are different (`net.ipv4.tcp_congestion_control` & `net.ipv4.tcp_slow_start_after_idle`) you rather I keep the LHN and add another "profile" for these two parameters, or do I add this to the existing LHN profile? @jhoblitt

I'd rather add those sysctls to the existing LHN profile as support USDF transfers is the intended function of that profile.

**Pull request closed without merging**
