### PR TITLE
(node/lsstcam-dc*.cp) update nodes configuration

### PR DESCRIPTION
**Pull request by dtapiacl**

### CODE REVIEW

**Comment by dtapiacl** [comment]
This PR updates the network configuration to pure YAML format and enables the lsst-daq interface fo all lsstcam nodes at the summit. Tests were also incorporated.

**Review by jhoblitt — CHANGES_REQUESTED** [review]
This is a lot of repetition.  Lets DRY this up a bit.  Perhaps with a variant layer?

**Comment by dtapiacl** [comment]
> This is a lot of repetition. Lets DRY this up a bit. Perhaps with a variant layer?

Cleaned this up by Squashing and creating a variant for this model of server.

**Review by jhoblitt — APPROVED** [review]
LGTM.

**Pull request merged**
