### PR TITLE
(role/foreman) migrate foreman_envsync hub.docker.com -> ghcr.io

### PR DESCRIPTION
**Pull request by jhoblitt**
Depends on:
- https://github.com/lsst-it/foreman_envsync/pull/16
- https://github.com/lsst-it/foreman_envsync/pull/17
- https://github.com/lsst-it/foreman_envsync/pull/18
- https://github.com/lsst-it/foreman_envsync/pull/19
- https://github.com/lsst-it/puppet-foreman_envsync/pull/7
- https://github.com/lsst-it/puppet-foreman_envsync/pull/8

### CODE REVIEW

**Review by cbarria — COMMENTED** [review]
is this failing because is checking in the new location and is not there yet?

**Comment by jhoblitt** [comment]
The registry location now exists but the v1.5.0 image tag doesn't. The 1.2.0 release of the lsst/foreman_envsync puppet mod also doesn't exist yet.

**Comment by jhoblitt** [comment]
I probably should have opened this PR as a draft and not added reviewers until CI was passing.  I'll convert it to a draft now and not request re-review until the dependent changes have been merged.

**Review by hreinking — APPROVED** [review]
lgtm

**Pull request merged**
