### PR TITLE
(profile::core::gpio) fwv

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Review by glennmorris — COMMENTED** [review]
I guess this is fine, assuming it will be a no-op on RHEL7?

**Comment by jhoblitt** [comment]
> I guess this is fine, assuming it will be a no-op on RHEL7?

Correct. There will be no char device to match the name pattern, so nothing will happen.

**Review by glennmorris — DISMISSED** [review]

**Comment by glennmorris** [comment]
Actually, now that I think about it, shouldn't this be part of the [ccs_hcu](https://github.com/lsst-it/puppet-ccs_hcu) module?

**Comment by jhoblitt** [comment]
@glennmorris I feel like this is really in role/profile territory.  We are going to use the same udev rules for rpis so I think I'm going to turn this into a profile class.

**Comment by jhoblitt** [comment]
This has been reworked to add a new `profile::core::gpio` profile.

**Review by glennmorris — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
