### PR TITLE
(profile::pi::gpshat) fwv

### PR DESCRIPTION
**Pull request by jhoblitt**
Depends on #1008

### CODE REVIEW

**Comment by jhoblitt** [comment]
I just realized pigpio is missing. I'm pulling this back from review.

**Comment by womullan** [comment]
looks ok but i guess this is more for @fritzm

**Review by cbarria — APPROVED** [review]
Looks Great 👍🏻

**Comment by jhoblitt** [comment]
@womullan Oops, I didn't intentionally add you as a reviewer. Sorry!

**Pull request merged**
