### PR TITLE
(ccs) install file-transfer utilities

### PR DESCRIPTION
**Pull request by glennmorris**
Adding this to site/profile/ccs since it already has the machinery for installing files from nexus

NB this requires https://github.com/lsst-it/lsst-puppet-hiera-private/pull/90

### CODE REVIEW

**Review by jhoblitt — COMMENTED** [review]
@glennmorris This looks reasonable.  Could we have at least some minimal spec coverage for the new class?

**Comment by glennmorris** [comment]
> @glennmorris This looks reasonable. Could we have at least some minimal spec coverage for the new class?

Something beyond the following?

https://github.com/lsst-it/lsst-control/pull/880/commits/668d8a3efc3cae89a64e7a15cd05b1c5b5315112
https://github.com/lsst-it/lsst-control/pull/880/commits/d2785d2b3e738f5adb70f58fa6ddc2220521fd22

**Comment by jhoblitt** [comment]
> > @glennmorris This looks reasonable. Could we have at least some minimal spec coverage for the new class?
> 
> Something beyond the following?
> 
> [668d8a3](https://github.com/lsst-it/lsst-control/commit/668d8a3efc3cae89a64e7a15cd05b1c5b5315112) [d2785d2](https://github.com/lsst-it/lsst-control/commit/d2785d2b3e738f5adb70f58fa6ddc2220521fd22)

There aren't any class level tests at all.  I do prefer the more functional tests of the results rather than all of the logic but it looks like there's a number of script files being installed that don't have coverage.

**Comment by glennmorris** [comment]
I've added some [tests](https://github.com/lsst-it/lsst-control/blob/IT-4662/ccs-file-transfer/spec/classes/ccs/file_transfer_spec.rb) for the class.

**Review by jhoblitt — APPROVED** [review]
This looks much improved. Thanks for putting in the effort. :+1:

**Pull request merged**
