### PR TITLE
(foreman.ls) Rename Kueyen Network to Ayekan

### PR DESCRIPTION
**Pull request by cbarria**
We are going to use the old network segment on Kueyen for the Observability Cluster Ayekan.

### CODE REVIEW

**Review by jhoblitt — COMMENTED** [review]
Is a full /25 needed for this cluster?

**Comment by cbarria** [comment]
the pool was shrink down to a /26 for a better fit

**Review by dtapiacl — APPROVED** [review]
Changes look good to me.

**Comment by julioconstanzo** [comment]
LGTM

**Review by julioconstanzo — APPROVED** [review]
I missed the approval. LGTM

**Review by jhoblitt — APPROVED** [review]

**Pull request merged**
