### PR TITLE
(node/lsstcam-db01) run ccs services localdb and rest-server

### PR DESCRIPTION
**Pull request by glennmorris**
I thought about doing this in role/ccs-database instead, but it seems ccs_software::services has no merge strategy set at present, so it would have been a more invasive change.

### CODE REVIEW

**Review by hreinking — APPROVED** [review]
lgtm

**Review by cbarria — CHANGES_REQUESTED** [review]
changes look good, but there are no test for the services added... they should be somewhere around:

`it { is_expected.to contain_class('Ccs_software::Service')}
  it { is_expected.to contain_service('rest-server')}
 it { is_expected.to contain_service('localdb')}`
 
 👍🏻

**Comment by jhoblitt** [comment]
As we haven't been requesting spec coverage of the `ccs_software` class parameters in the past, and there are no existing examples in the tree, I've added some commits to this branch which add this coverage.  I have also rebased on current `production`.

**Review by cbarria — APPROVED** [review]
Looks Great 👍🏻

**Review by jhoblitt — APPROVED** [review]

**Pull request merged**
