### PR TITLE
(role/ccs-hcu-fb) new specialized ccs hcu role

### PR DESCRIPTION
**Pull request by glennmorris**

### CODE REVIEW

**Review by jhoblitt — COMMENTED** [review]
Would it make sense to have a  -fb role since there are multiple hosts with the same services?

**Comment by glennmorris** [comment]
> Would it make sense to have a -fb role since there are multiple hosts with the same services?

OK, I've redone it by adding a new role.

**Review by jhoblitt — APPROVED** [review]
This is acceptable but note that there is a catchall for roles which don't have a specific spec file.  This means every role added without a corresponding spec file will extended the length of the CI run since catchall doesn't parallelize.

**Comment by glennmorris** [comment]
> This is acceptable but note that there is a catchall for roles which don't have a specific spec file. This means every role added without a corresponding spec file will extended the length of the CI run since catchall doesn't parallelize.

I've now added a basic spec file.

**Pull request merged**
