### PR TITLE
(cluster/yagan) add VLAN1702 to yagan

### PR DESCRIPTION
**Pull request by cbarria**
add IPSEC VLAN into yagan so we can move services and dump VLAN1800 (lhn)

### CODE REVIEW

**Review by jhoblitt — CHANGES_REQUESTED** [review]
NACK.  We discussed last week moving vlan1800 to the ipsec tunnel.

**Comment by gseriche** [comment]
> NACK. We discussed last week moving vlan1800 to the ipsec tunnel.

@jhoblitt  this is for VLAN1702 not for VLAN1800.

**Review by gseriche — DISMISSED** [review]
lgtm

**Comment by jhoblitt** [comment]
> > NACK. We discussed last week moving vlan1800 to the ipsec tunnel.
> 
> @jhoblitt this is for VLAN1702 not for VLAN1800.

That is exactly my objection.  We do not need to add a new vlan to migrate everything from vlan1800 over to.

**Comment by gseriche** [comment]
> > > NACK. We discussed last week moving vlan1800 to the ipsec tunnel.
> > 
> > 
> > @jhoblitt this is for VLAN1702 not for VLAN1800.
> 
> That is exactly my objection. We do not need to add a new vlan to migrate everything from vlan1800 over to.

I missed the context then; my apologies. @cbarria, why do we need a new VLAN?

**Comment by cbarria** [comment]
this was cancelled, they are deploying the squid either way 😭

**Pull request closed without merging**
