### PR TITLE
(node/hvac.cp.lsst.org) add el9 host

### PR DESCRIPTION
**Pull request by dtapiacl**

### CODE REVIEW

**Review by badenerb — DISMISSED** [review]
Please put host in IPAM

**Review by csilva-cl — APPROVED** [review]
looks good

**Comment by dtapiacl** [comment]
> Please put host in IPAM

https://ipam.cp.lsst.org/index.php?page=subnets&section=1&subnetId=8&sPage=address-details&ipaddrid=3810

**Review by badenerb — APPROVED** [review]
LGTM!

**Pull request merged**
