### PR TITLE
(node/lsstcam-daq-mgt.cp) provision host EL8

### PR DESCRIPTION
**Pull request by dtapiacl**

### CODE REVIEW

**Comment by dtapiacl** [comment]
lsstcam-daq-mgt.cp.lsst.org was added to IPAM and device was linked to a Device.

**Review by jhoblitt — CHANGES_REQUESTED** [review]
Please add this device to ipam and associate the IP addresses with it.

The commits should be squashed together or the testing commit should have a more descriptive title.

**Comment by dtapiacl** [comment]
> Please add this device to ipam and associate the IP addresses with it.
> 
> The commits should be squashed together or the testing commit should have a more descriptive title.

Updated commit message to be more descriptive. Device is already associated in ipam.cp.lsst.org

**Review by jhoblitt — COMMENTED** [review]
LGTM.

**Review by jhoblitt — APPROVED** [review]

**Pull request merged**
